In [2]:
x = 2
x

2

In [10]:
x = [1,2,3]
y =x

In [11]:
print(y)
print(x)

[1, 2, 3]
[1, 2, 3]


In [12]:
x.append(4)
print(x)
print(y)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [14]:
x = 10
y = x

In [17]:
x += 6

In [18]:
print(x)  #X has been assigned 
print(y)  #y has not been updated with new value

16
10


In [20]:
x= "hello"
type(x)

str

In [21]:
x = 3.1479
type(x)

float

In [22]:
x.is_integer()

False

In [23]:
# Boolean operations
x = 4
(x <6) and (x>1)

True

In [24]:
(x<2) or (x%2==0)

True

In [25]:
not(x < 6)

False

In [30]:
# Identity and membership operations
# is, in and not

a = 'hello'
b = a
print(a is b)
print(a is not b)

True
False


In [29]:
a = [1]
c = 1
b = [1,2,3,4]
print(a in b)
print(c in b)

False
True


In [31]:
# Built in types
# int, float, complex, bool, string and NONETYPE

# Mutable - object can be changed after it is created e.g. Lists, sets and dictionaries
# Immutable - object can not be changed after it is created e.g. Boolean, integers, floats, strings, frozensets and tuples

complex(1,3)

(1+3j)

In [32]:
(1+6j) * (2 - 6j)

(38+6j)

In [33]:
message = "What do you like? "

In [34]:
len(message)

18

In [35]:
print(message.upper())
print(message.lower())

WHAT DO YOU LIKE? 
what do you like? 


In [36]:
response = " Ice cream!! "

message + response

In [38]:
response * 5

' Ice cream!!  Ice cream!!  Ice cream!!  Ice cream!!  Ice cream!! '

In [40]:
type(None)

NoneType

In [41]:
returntype = print("abc")
returntype

abc


In [44]:
print(type(returntype))
print(returntype)

<class 'NoneType'>
None


In [55]:
# Non primitive Data Structures
# Lists, tuples, dictionaries, Sets

L1 = []
L2 = [1, "microsoft", 10, "apple"]
L3 = [9,3,5,6,3,5,8,2,3,1]
print(L2[3])

L3.append(0)
print(L3)

L3.insert(5,5.5)
print(L3)

L3.sort()
print(L3)

L3.reverse()
print(L3)

L3.remove(3) ## removed element 3 not index 3
print(L3)  



apple
[9, 3, 5, 6, 3, 5, 8, 2, 3, 1, 0]
[9, 3, 5, 6, 3, 5.5, 5, 8, 2, 3, 1, 0]
[0, 1, 2, 3, 3, 3, 5, 5, 5.5, 6, 8, 9]
[9, 8, 6, 5.5, 5, 5, 3, 3, 3, 2, 1, 0]
[9, 8, 6, 5.5, 5, 5, 3, 3, 2, 1, 0]


In [77]:
import array as Ar
a1 = Ar.array("I",[5,8,1])
print(type(a1))

a2 = Ar.array("u", ["l", "k", "u"])
a2.tostring()

<class 'array.array'>


b'l\x00k\x00u\x00'

In [85]:
import numpy as np
a3 = np.array([3,6,9,12])
a4 = a3/3
print(a4)

a5 = np.ones(4)
print(a5)

a6 = np.ones([3,4])
print("matrix : ", a6)


[1. 2. 3. 4.]
[1. 1. 1. 1.]
matrix :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [89]:
# TUPLES

a = (1, 2, "a")
b = ("d", "u", "s", "k")

print(a[0])
print(b[2])

1
s


In [91]:
b[2] = "j"  # doesnot support change

TypeError: 'tuple' object does not support item assignment

In [103]:
# Dictionary - combinations of keys and values, not by position only by indexes

d = {"a":1, "b":2}

print(d)
print(d["b"])

del(d["b"])
print(d)

print(d.keys())
print(d.values())

{'a': 1, 'b': 2}
2
{'a': 1}
dict_keys(['a'])
dict_values([1])


In [105]:
# Frozendict

from frozendict import frozendict
fd = frozendict({"one": 1})

print(fd)
print(fd["one"])
print(fd.copy(another="data science"))

ModuleNotFoundError: No module named 'frozendict'

In [109]:
# SETS
s1 = set('TEXASANDINSTRUMENTS')
s2 = set('dsukdsukTENTS')

print("or elements: " , s1|s2)
print("and elements: ", s1 & s2)

or elements:  {'E', 'u', 'S', 'T', 'd', 'k', 'D', 'A', 'U', 'N', 's', 'M', 'I', 'R', 'X'}
and elements:  {'E', 'S', 'T', 'N'}


In [ ]:
# FROZEN SETS : immutable

fs= frozenset("animalkingdom")

In [120]:
# loops

for N in [2,3,4,5]:
    print(N, end = ' ')

2 3 4 5 

In [121]:
i = 0
while i < 10:
    i += 1
    #print(i) #gives new line
    print(i, end = ' ')  # result in same line
    

1 2 3 4 5 6 7 8 9 10 

In [122]:
range(20)

range(0, 20)

In [126]:
for i in range(20):
    if(i%2 == 0):
        continue 
    print(i, end = ' ')

1 3 5 7 9 11 13 15 17 19 

In [137]:
a,b = 0,1

amax= 100
L1 = [a]

while True:
    a,b=b,a+b
    if(b>amax):
        break
    L1.append(b)
    
print(L1)

[0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [141]:
# Functions

def fibonacci(N):
    L = [0]
    a,b = 0,1
    
    while len(L) < N:
        a, b = b, a+b
        L.append(a)
    return L

In [142]:
fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [150]:
# *args, **kwargs

def catch_all(*args, **kwargs):
    print("args are :" , args)
    print("kwargs are: ", kwargs)
    

In [151]:
catch_all(1,2,3, a = 6, b = 10)

args are : (1, 2, 3)
kwargs are:  {'a': 6, 'b': 10}


In [152]:
add = lambda x,y: x+y
add(10,20)

30

In [157]:
# Errors and Exceptions
#print(Q)
#print(2/0)

L = [0,1,2,3]
L[100]

IndexError: list index out of range

In [160]:
try:
    print("this is first")
    print(k)
except:
    print("this is second")
    
    

this is first
this is second


In [161]:
raise RuntimeError("My error")

RuntimeError: My error

In [162]:
# Raising error

def fibonacci_new(N):
    if(N<0):
        raise RuntimeError("N cannot be negative")
    L = [0]
    a,b = 0,1
    
    while len(L) < N:
        a, b = b, a+b
        L.append(a)
    return L

In [163]:
fibonacci_new(-9)

RuntimeError: N cannot be negative